version: "3.5"

services:
  back-end:
    container_name: back-end
    build: ./requirements/back-end
    image: back-end
    networks:
      - dnet
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - jsData:/home/Projects/NestFirst

  postgres:
    container_name: postgres
    image: postgres:13
    networks:
      - dnet
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgData:/var/lib/postgresql/data

networks:
  dnet:
    driver: bridge

volumes:
  pgData:
    driver: local
  jsData:
    driver: local
    name: jsData 
    driver_opts:
      type: none
      o: bind
      device: /mnt/nfs/homes/abrun/Projects/Transcendence/srcs/volumes/NestFirst
