version: "3.5"

services:
  back-end:
    container_name: back-end
    build: ./requirements/back-end
    image: back-end
    networks:
      - dnet
    ports:
      - "3001:3001"
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - jsData:/home/Projects/NestFirst

  postgres:
    container_name: postgres
    image: postgres:13
    networks:
      - dnet
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgData:/var/lib/postgresql/data

  front-end:
    container_name: front-end
    build: ./requirements/front-end
    image: front-end
    networks:
      - dnet
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - rtData:/home/Projects/react-websocket

networks:
  dnet:
    driver: bridge

volumes:
  pgData:
    driver: local
  jsData:
    driver: local
    name: jsData 
    driver_opts:
      type: none
      o: bind
      device: /mnt/nfs/homes/abrun/Projects/My_transcendence/srcs/volumes/NestFirst
  rtData:
    driver: local
    name: rtData 
    driver_opts:
      type: none
      o: bind
      device: /mnt/nfs/homes/abrun/Projects/My_transcendence/srcs/volumes/react-websocket
